// packages/grommet/src/App.tsx
import { Button, Menu, Tab, Tabs, Toolbar } from "grommet";
import { useEffect, useMemo, useState } from "react";
import BuildInfo from "./BuildInfo";
import Extension from "./Extension";
import Extensions from "./Extensions";
import ServerInfo from "./ServerInfo";
import { isExtensionInfo } from "./utils";

const Environment = {
  Public: "https://hosting.portal.azure.net/api/diagnostics",
  Fairfax: "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics",
  Mooncake: "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics",
} as const;

const App: React.FC = () => {
  const [diagnostics, setDiagnostics] = useState<Diagnostics>();
  const [extension, setExtension] = useState<ExtensionInfo>();
  const [environment, setEnvironment] = useState<string>(Environment.Public);
  const [activeIndex, setActiveIndex] = useState<number>(0);

  const environmentName = useMemo(() => {
    switch (environment) {
      case Environment.Public:
        return "Public Cloud";
      case Environment.Fairfax:
        return "Fairfax";
      case Environment.Mooncake:
        return "Mooncake";
      default:
        return "Select environment";
    }
  }, [environment]);

  const showPaasServerless = useMemo(
    () => isExtensionInfo(diagnostics?.extensions["paasserverless"]),
    [diagnostics?.extensions]
  );

  const environments = useMemo(
    () => [
      {
        key: "public",
        text: "Public Cloud",
        selected: environment === Environment.Public,
        onClick: () => {
          setEnvironment(Environment.Public);
          setExtension(undefined);
        },
      },
      {
        key: "fairfax",
        text: "Fairfax",
        selected: environment === Environment.Fairfax,
        onClick: () => {
          setEnvironment(Environment.Fairfax);
          setExtension(undefined);
        },
      },
      {
        key: "mooncake",
        text: "Mooncake",
        selected: environment === Environment.Mooncake,
        onClick: () => {
          setEnvironment(Environment.Mooncake);
          setExtension(undefined);
        },
      },
    ],
    [environment]
  );

  useEffect(() => {
    (async () => {
      const response = await fetch(environment);
      setDiagnostics(await response.json());
    })();
  }, [environment]);

  if (!diagnostics) {
    return null;
  }

  const { buildInfo, extensions, serverInfo } = diagnostics;

  const handleLinkClick = (_?: React.MouseEvent, item?: KeyedNavLink) => {
    if (item) {
      const extension = extensions[item.key];
      if (isExtensionInfo(extension)) {
        setExtension(extension);
      }
    }
  };

  return (
    <div className="flexbox">
      <Toolbar align="center">
        <Menu
          label={environmentName}
          items={environments.map((env) => ({
            label: env.text,
            onClick: env.onClick,
          }))}
        />
        {showPaasServerless && (
          <Button
            label="paasserverless"
            plain
            onClick={() => {
              const paasserverless = diagnostics?.extensions["paasserverless"];
              if (isExtensionInfo(paasserverless)) {
                setExtension(paasserverless);
              }
            }}
          />
        )}
        <Button
          label="websites"
          plain
          onClick={() => {
            const websites = diagnostics?.extensions["websites"];
            if (isExtensionInfo(websites)) {
              setExtension(websites);
            }
          }}
        />
      </Toolbar>
      <Tabs activeIndex={activeIndex} justify="start" onActive={setActiveIndex}>
        <Tab title="Extensions" />
        <Tab title="Build Information" />
        <Tab title="Server Information" />
      </Tabs>
      {activeIndex === 0 && (
        <div className="tab-panel">
          <div className="stack">
            <Extensions extensions={extensions} onLinkClick={handleLinkClick} />
            {extension && <Extension {...extension} />}
          </div>
        </div>
      )}
      {activeIndex === 1 && (
        <div className="tab-panel">
          <BuildInfo {...buildInfo} />
        </div>
      )}
      {activeIndex === 2 && (
        <div className="tab-panel">
          <ServerInfo {...serverInfo} />
        </div>
      )}
    </div>
  );
};

export default App;

// packages/material/src/components/App/App.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatTabsModule } from '@angular/material/tabs';
import { MatToolbarModule } from '@angular/material/toolbar';
import { DiagnosticsService } from '../../app/diagnostics.service';
import { isExtensionInfo } from '../../utils/index';
import { BuildInfoComponent } from '../BuildInfo/BuildInfo.component';
import { ExtensionComponent } from '../Extension/Extension.component';
import { ExtensionsComponent } from '../Extensions/Extensions.component';
import { ServerInfoComponent } from '../ServerInfo/ServerInfo.component';

export enum Environment {
  Public = 'https://hosting.portal.azure.net/api/diagnostics',
  Fairfax = 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics',
  Mooncake = 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics',
}

@Component({
  selector: 'app-component',
  templateUrl: './App.component.html',
  styleUrls: ['./App.component.css'],
  imports: [
    CommonModule,
    BuildInfoComponent,
    ExtensionComponent,
    ExtensionsComponent,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    MatTabsModule,
    MatToolbarModule,
    ServerInfoComponent,
  ],
})
export class AppComponent implements OnInit {
  diagnostics?: Diagnostics;
  extension?: ExtensionInfo;
  environment: Environment = Environment.Public;
  selectedIndex = 0;

  private diagnosticsService = inject(DiagnosticsService);

  get environmentName(): string {
    switch (this.environment) {
      case Environment.Public:
        return 'Public Cloud';
      case Environment.Fairfax:
        return 'Fairfax';
      case Environment.Mooncake:
        return 'Mooncake';
    }
  }

  environments = [
    {
      key: 'public',
      text: 'Public Cloud',
      selected: () => this.environment === Environment.Public,
      onClick: () => {
        this.setEnvironment(Environment.Public);
      },
    },
    {
      key: 'fairfax',
      text: 'Fairfax',
      selected: () => this.environment === Environment.Fairfax,
      onClick: () => {
        this.setEnvironment(Environment.Fairfax);
      },
    },
    {
      key: 'mooncake',
      text: 'Mooncake',
      selected: () => this.environment === Environment.Mooncake,
      onClick: () => {
        this.setEnvironment(Environment.Mooncake);
      },
    },
  ];

  get showPaasServerless(): boolean {
    return isExtensionInfo(this.diagnostics?.extensions?.['paasserverless']);
  }

  async ngOnInit() {
    this.diagnostics = await this.diagnosticsService.fetchDiagnostics(
      this.environment,
    );
  }

  async setEnvironment(env: Environment) {
    this.environment = env;
    this.extension = undefined;
    this.diagnostics = await this.diagnosticsService.fetchDiagnostics(
      this.environment,
    );
  }

  handleLinkClick(item?: KeyedNavLink) {
    if (item) {
      const extension = this.diagnostics?.extensions[item.key];
      if (isExtensionInfo(extension)) {
        this.extension = extension;
      }
    }
  }

  selectExtension(key: string) {
    const ext = this.diagnostics?.extensions[key];
    if (isExtensionInfo(ext)) {
      this.extension = ext;
    }
  }
}

<div class="flexbox">
  <mat-toolbar>
    <mat-menu #envMenu="matMenu">
      @for (env of environments; track env) {
        <button mat-menu-item (click)="env.onClick()">
          <mat-icon>
            {{ env.selected() ? 'check' : '' }}
          </mat-icon>
          {{ env.text }}
        </button>
      }
    </mat-menu>
    <button mat-button [matMenuTriggerFor]="envMenu">
      {{ environmentName }}
    </button>
    @if (showPaasServerless) {
      <button mat-button (click)="selectExtension('paasserverless')">
        paasserverless
      </button>
    }
    <button mat-button (click)="selectExtension('websites')">websites</button>
  </mat-toolbar>

  <mat-tab-group mat-stretch-tabs="false" [(selectedIndex)]="selectedIndex">
    <mat-tab label="Extensions"></mat-tab>
    <mat-tab label="Build Information"></mat-tab>
    <mat-tab label="Server Information"></mat-tab>
  </mat-tab-group>

  @if (selectedIndex === 0) {
    <div class="tab-panel">
      <div class="stack">
        <app-extensions
          [extensions]="diagnostics?.extensions ?? {}"
          (linkClick)="handleLinkClick($event.item)"
        />
        @if (extension) {
          <app-extension
            [config]="extension.config"
            [extensionName]="extension.extensionName"
            [stageDefinition]="extension.stageDefinition"
          />
        }
      </div>
    </div>
  } @else if (selectedIndex === 1) {
    <div class="tab-panel">
      @if (diagnostics?.buildInfo) {
        <app-build-info [buildVersion]="diagnostics?.buildInfo.buildVersion" />
      }
    </div>
  } @else if (selectedIndex === 2) {
    <div class="tab-panel">
      @if (diagnostics?.serverInfo) {
        <app-server-info [serverInfo]="diagnostics?.serverInfo" />
      }
    </div>
  }
</div>
