// packages/smui/src/lib/components/BuildInfo.svelte
<script lang="ts">
	const { buildVersion }: BuildInfoProps = $props();

	const items = $derived([{ name: 'Build Version', value: buildVersion }]);
</script>

<table aria-label="Build Info">
	<thead>
		<tr>
			<th class="mdc-typography--headline6">Name</th>
			<th class="mdc-typography--headline6">Value</th>
		</tr>
	</thead>
	<tbody>
		{#each items as item (item.name)}
			<tr>
				<td class="mdc-typography--body1">{item.name}</td>
				<td class="mdc-typography--body1">{item.value}</td>
			</tr>
		{/each}
	</tbody>
</table>

// packages/blueprint/src/BuildInfo.tsx
import { HTMLTable } from "@blueprintjs/core";

const BuildInfo: React.FC<BuildInfoProps> = ({ buildVersion }) => {
  const items = [
    {
      name: "Build Version",
      value: buildVersion,
    },
  ];

  return (
    <HTMLTable aria-label="Build Info">
      <thead>
        <tr>
          <th>Name</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        {items.map((item) => (
          <tr key={item.name}>
            <td>{item.name}</td>
            <td>{item.value}</td>
          </tr>
        ))}
      </tbody>
    </HTMLTable>
  );
};

export default BuildInfo;
