// packages/smui/src/lib/components/Configuration.svelte
<script lang="ts">
	const { config }: ConfigurationProps = $props();

	const items = $derived(
		Object.entries(config).map(([key, value]) => ({ key, value }))
	);
</script>

<div>
	<h2 id="configuration" class="mdc-typography--headline5">Configuration</h2>
	<table aria-labelledby="configuration">
		<thead>
			<tr>
				<th class="mdc-typography--headline6">Key</th>
				<th class="mdc-typography--headline6">Value</th>
			</tr>
		</thead>
		<tbody>
			{#each items as item (item.key)}
				<tr>
					<td class="mdc-typography--body1">{item.key}</td>
					<td class="mdc-typography--body1">{item.value}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>

// packages/blueprint/src/Configuration.tsx
import { HTMLTable } from "@blueprintjs/core";

const Configuration: React.FC<ConfigurationProps> = ({ config }) => {
  const items = Object.entries(config).reduce<KeyValuePair<string>[]>(
    (previous, [key, value]) => [...previous, { key, value }],
    []
  );

  return (
    <div>
      <h3 className="bp6-heading">Configuration</h3>
      <HTMLTable aria-label="Configuration">
        <thead>
          <tr>
            <th>Key</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <tr key={item.key}>
              <td>{item.key}</td>
              <td>{item.value}</td>
            </tr>
          ))}
        </tbody>
      </HTMLTable>
    </div>
  );
};

export default Configuration;
