// packages/smui/src/lib/components/StageDefinition.svelte
<script lang="ts">
	const { stageDefinition }: StageDefinitionProps = $props();

	const items = $derived(
		Object.entries(stageDefinition).map(([key, value]) => ({ key, value }))
	);
</script>

<div>
	<h2 id="stage-definitions" class="mdc-typography--headline5">
		Stage Definitions
	</h2>
	<table aria-labelledby="stage-definitions">
		<thead>
			<tr>
				<th class="mdc-typography--headline6">Key</th>
				<th class="mdc-typography--headline6">Value</th>
			</tr>
		</thead>
		<tbody>
			{#each items as item (item.key)}
				<tr>
					<td class="mdc-typography--body1">{item.key}</td>
					<td class="mdc-typography--body1">{item.value.join(', ')}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>

// packages/blueprint/src/StageDefinition.tsx
import { HTMLTable } from "@blueprintjs/core";

const StageDefinition: React.FC<StageDefinitionProps> = ({
  stageDefinition,
}) => {
  const items = Object.entries(stageDefinition).reduce<
    KeyValuePair<string[]>[]
  >((previous, [key, value]) => [...previous, { key, value }], []);

  return (
    <div>
      <h3 className="bp6-heading">Stage Definitions</h3>
      <HTMLTable aria-label="Stage Definitions">
        <thead>
          <tr>
            <th>Key</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <tr key={item.key}>
              <td>{item.key}</td>
              <td>{item.value.join(", ")}</td>
            </tr>
          ))}
        </tbody>
      </HTMLTable>
    </div>
  );
};

export default StageDefinition;
