// packages/nuxt-ui/app/app.vue
<template>
  <div
    class="flex flex-col h-screen transition-opacity"
    :class="{ 'opacity-0': !mounted }"
  >
    <UFieldGroup class="p-1">
      <UDropdownMenu :items="environments" mode="click">
        <UButton color="neutral" icon="i-lucide-chevron-down" variant="outline">
          {{ environmentName }}
        </UButton>
      </UDropdownMenu>
      <UButton
        v-if="showPaasServerless"
        @click="selectExtension('paasserverless')"
      >
        paasserverless
      </UButton>
      <UButton @click="selectExtension('websites')">websites</UButton>
    </UFieldGroup>

    <UProgress v-if="pending" mode="indeterminate" />

    <UAlert v-else-if="error" color="error" :title="error.message" />

    <template v-else>
      <UTabs
        v-model="selectedTab"
        :items="tabs"
        justify="start"
        variant="link"
      />

      <div v-if="selectedTab === 'extensions'" class="tab-panel">
        <div class="stack">
          <ExtensionItems
            v-if="diagnostics?.extensions"
            :extensions="diagnostics?.extensions"
            :on-link-click="handleLinkClick"
          />
          <ExtensionItem v-if="selectedExtension" v-bind="selectedExtension" />
        </div>
      </div>

      <div v-else-if="selectedTab === 'build'" class="tab-panel">
        <BuildInfo
          v-if="diagnostics?.buildInfo"
          v-bind="diagnostics?.buildInfo"
        />
      </div>

      <div v-else-if="selectedTab === 'server'" class="tab-panel">
        <ServerInfo
          v-if="diagnostics?.serverInfo"
          v-bind="diagnostics?.serverInfo"
        />
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { isExtensionInfo } from "~/utils/extensions";
import type { Diagnostics, ExtensionInfo, KeyedNavLink } from "~/types";
import type { DropdownMenuItem, TabsItem } from "@nuxt/ui";

type Environment =
  | "https://hosting.portal.azure.net/api/diagnostics"
  | "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics"
  | "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics";

const Environments = {
  Public: "https://hosting.portal.azure.net/api/diagnostics",
  Fairfax: "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics",
  Mooncake: "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics",
} as const;

const selectedExtension = ref<ExtensionInfo>();
const currentEnvironment = ref<Environment>(Environments.Public);
const selectedTab = ref<string>("extensions");
const mounted = ref(false);

const diagnosticsUrl = computed(() => currentEnvironment.value);

const {
  data: diagnostics,
  pending,
  error,
} = useFetch<Diagnostics>(diagnosticsUrl);

const environmentName = computed(() => {
  switch (currentEnvironment.value) {
    case Environments.Public:
      return "Public Cloud";
    case Environments.Fairfax:
      return "Fairfax";
    case Environments.Mooncake:
      return "Mooncake";
    default:
      return "Select environment";
  }
});

const showPaasServerless = computed(() =>
  isExtensionInfo(diagnostics.value?.extensions["paasserverless"])
);

const environments = computed<DropdownMenuItem[]>(() => [
  {
    label: "Public Cloud",
    onSelect: () => switchEnvironment(Environments.Public),
  },
  {
    label: "Fairfax",
    onSelect: () => switchEnvironment(Environments.Fairfax),
  },
  {
    label: "Mooncake",
    onSelect: () => switchEnvironment(Environments.Mooncake),
  },
]);

const tabs = computed<TabsItem[]>(() => [
  { label: "Extensions", value: "extensions" },
  { label: "Build Information", value: "build" },
  { label: "Server Information", value: "server" },
]);

function switchEnvironment(env: Environment) {
  currentEnvironment.value = env;
  selectedExtension.value = undefined;
}

function handleLinkClick(_: MouseEvent, item?: KeyedNavLink) {
  if (item && diagnostics.value?.extensions) {
    const extension = diagnostics.value.extensions[item.key];
    if (isExtensionInfo(extension)) {
      selectedExtension.value = extension;
    }
  }
}

function selectExtension(key: string) {
  const extension = diagnostics.value?.extensions[key];
  if (isExtensionInfo(extension)) {
    selectedExtension.value = extension;
  }
}

onMounted(() => {
  mounted.value = true;
});
</script>

// packages/antd/src/App.tsx
import { Empty, Flex, Menu, Spin, Tabs } from "antd";
import { Activity, useCallback, useMemo, useState } from "react";
import useSWR from "swr";
import BuildInfo from "./BuildInfo";
import Extension from "./Extension";
import Extensions from "./Extensions";
import ServerInfo from "./ServerInfo";
import { isExtensionInfo, when } from "./utils";

import "./App.css";

const Environment = {
  Public: "https://hosting.portal.azure.net/api/diagnostics",
  Fairfax: "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics",
  Mooncake: "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics",
} as const;

type EnvironmentUrl = (typeof Environment)[keyof typeof Environment];

const items = [
  { key: "extensions", label: "Extensions" },
  { key: "build", label: "Build Information" },
  { key: "server", label: "Server Information" },
];

const App: React.FC = () => {
  const [extension, setExtension] = useState<ExtensionInfo>();
  const [environment, setEnvironment] = useState<EnvironmentUrl>(
    Environment.Public
  );
  const [selectedTab, setSelectedTab] = useState("extensions");

  const {
    data: diagnostics,
    error,
    isLoading,
  } = useSWR<Diagnostics>(environment, async (environment: string) => {
    const response = await fetch(environment);

    if (!response.ok) {
      throw new Error(`Error fetching diagnostics: ${response.statusText}`);
    }

    return response.json();
  });

  const environmentName = useMemo(() => {
    switch (environment) {
      case Environment.Public:
        return "Public Cloud";
      case Environment.Fairfax:
        return "Fairfax";
      case Environment.Mooncake:
        return "Mooncake";
      default:
        return "Select environment";
    }
  }, [environment]);

  const showPaasServerless = useMemo(
    () => isExtensionInfo(diagnostics?.extensions["paasserverless"]),
    [diagnostics?.extensions]
  );

  const environments = useMemo(
    () => [
      {
        key: "public",
        text: "Public Cloud",
        selected: environment === Environment.Public,
        onClick: () => {
          setEnvironment(Environment.Public);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
      {
        key: "fairfax",
        text: "Fairfax",
        selected: environment === Environment.Fairfax,
        onClick: () => {
          setEnvironment(Environment.Fairfax);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
      {
        key: "mooncake",
        text: "Mooncake",
        selected: environment === Environment.Mooncake,
        onClick: () => {
          setEnvironment(Environment.Mooncake);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
    ],
    [environment]
  );

  const menuItems = useMemo(
    () => [
      {
        key: "env-dropdown",
        label: environmentName,
        children: environments.map((env) => ({
          key: env.key,
          label: env.text,
          onClick: env.onClick,
        })),
      },
      ...when(showPaasServerless, {
        key: "paasserverless",
        label: "paasserverless",
        onClick: () => {
          const paasserverless = diagnostics?.extensions["paasserverless"];
          if (isExtensionInfo(paasserverless)) {
            setExtension(paasserverless);
            setSelectedTab("extensions");
          }
        },
      }),
      {
        key: "websites",
        label: "websites",
        onClick: () => {
          const websites = diagnostics?.extensions["websites"];
          if (isExtensionInfo(websites)) {
            setExtension(websites);
            setSelectedTab("extensions");
          }
        },
      },
    ],
    [environments, environmentName, showPaasServerless, diagnostics?.extensions]
  );

  const handleLinkClick = useCallback(
    (_?: React.MouseEvent, item?: KeyedNavLink) => {
      if (item) {
        const extension = diagnostics?.extensions[item.key];
        if (isExtensionInfo(extension)) {
          setExtension(extension);
        }
      }
    },
    [diagnostics?.extensions]
  );

  return (
    <div className="flexbox">
      <Menu mode="horizontal" items={menuItems} />
      <Tabs
        activeKey={selectedTab}
        className="tab-list"
        items={items}
        onChange={(key) => setSelectedTab(key)}
      />
      <Activity mode={isLoading ? "visible" : "hidden"}>
        <div className="tab-panel">
          <Flex className="centered">
            <Spin size="large" />
          </Flex>
        </div>
      </Activity>
      <Activity mode={error && !isLoading ? "visible" : "hidden"}>
        {error && (
          <div className="tab-panel">
            <Flex className="centered">
              <Empty
                description={`Error: ${error.message ?? "Unexpected error"}`}
              />
            </Flex>
          </div>
        )}
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "extensions"
            ? "visible"
            : "hidden"
        }
      >
        {diagnostics?.extensions && (
          <div className="tab-panel">
            <Flex className="stack">
              <Extensions
                extensions={diagnostics.extensions}
                onLinkClick={handleLinkClick}
              />
              {extension && <Extension {...extension} />}
            </Flex>
          </div>
        )}
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "build" ? "visible" : "hidden"
        }
      >
        {diagnostics?.buildInfo && (
          <div className="tab-panel">
            <BuildInfo {...diagnostics.buildInfo} />
          </div>
        )}
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "server"
            ? "visible"
            : "hidden"
        }
      >
        {diagnostics?.buildInfo && (
          <div className="tab-panel">
            <ServerInfo {...diagnostics.serverInfo} />
          </div>
        )}
      </Activity>
    </div>
  );
};

export default App;
