// packages/carbon/src/lib/components/Configuration.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { config }: ConfigurationProps = $props();

	const headers = [
		{ key: 'key', value: 'Key', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived(Object.entries(config).map(([key, value]) => ({ id: key, key, value })));
</script>

<h2 id="configuration">Configuration</h2>
<DataTable aria-labelledby="configuration" {headers} {rows} />

// packages/naive/app/components/Configuration.vue
<template>
  <div>
    <n-h2>Configuration</n-h2>
    <n-data-table :columns="columns" :data="rows" size="small" />
  </div>
</template>

<script setup lang="ts">
import type { ConfigurationProps } from "@/types/ConfigurationProps"

const props = defineProps<ConfigurationProps>()

const columns = [
  { title: "Key", key: "key" },
  { title: "Value", key: "value" }
]

const rows = computed(() =>
  Object.entries(props.config ?? {}).map(([key, value]) => ({ key, value }))
)
</script>
