// packages/carbon/src/lib/components/StageDefinition.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { stageDefinition }: StageDefinitionProps = $props();

	const headers = [
		{ key: 'key', value: 'Key', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived(
		Object.entries(stageDefinition).map(([key, value]) => ({
			id: key,
			key,
			value: value.join(', ')
		}))
	);
</script>

<h2 id="stage-definitions">Stage Definition</h2>
<DataTable aria-labelledby="stage-definitions" {headers} {rows} />

// packages/bootstrap-vue/app/components/StageDefinition.vue
<template>
  <div>
    <h2>Stage Definitions</h2>
    <BTable :items="rows" :fields="fields" small />
  </div>
</template>

<script setup lang="ts">
import type { StageDefinitionProps } from "@/types/StageDefinitionProps";

const props = defineProps<StageDefinitionProps>();

const fields = [
  { key: "key", label: "Key" },
  { key: "value", label: "Value" }
];

const rows = computed(() =>
  Object.entries(props.stageDefinition ?? {}).map(([key, value]) => ({
    key,
    value: value.join(", ")
  }))
);
</script>
