// packages/naive/app/components/Extensions.vue
<template>
  <nav class="extensions" aria-label="Extensions">
    <n-space vertical>
      <n-button v-for="link in links" :key="link.key" text @click="handleClick(link)">{{
        link.name
      }}</n-button>
    </n-space>
  </nav>
</template>

<script setup lang="ts">
import type { ExtensionsProps, KeyedNavLink } from "@/types/ExtensionsProps"
import { byKey, isExtensionInfo, toNavLink } from "~/utils/extensions"

const props = defineProps<ExtensionsProps>()

const links = computed(() =>
  Object.values(props.extensions ?? {})
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey)
)

function handleClick(link: KeyedNavLink) {
  props.onLinkClick?.(link)
}
</script>

<style scoped>
.extensions {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  max-height: max-content;
  overflow-x: hidden;
  overflow-y: auto;
  padding: 0.5rem;
}
</style>

// packages/svelteui/src/Extensions.svelte
<script lang="ts">
  import { Button } from '@svelteuidev/core'
  import { createEventDispatcher } from 'svelte'
  import type {
    Extension,
    ExtensionInfo,
    ExtensionsProps,
    KeyedNavLink
  } from './types'

  export let extensions: ExtensionsProps['extensions']
  export let onLinkClick: ExtensionsProps['onLinkClick'] | undefined

  const dispatch = createEventDispatcher<{
    linkClick: { event: Event; link: KeyedNavLink }
  }>()

  // Utility functions
  function isExtensionInfo(extension: Extension): extension is ExtensionInfo {
    return 'extensionName' in extension
  }

  function toNavLink(extension: ExtensionInfo): KeyedNavLink {
    return {
      key: extension.extensionName,
      name: extension.extensionName,
      url: extension.extensionName
    }
  }

  function byKey(a: KeyedNavLink, b: KeyedNavLink): number {
    return a.key.localeCompare(b.key)
  }

  $: links = Object.values(extensions)
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey)

  function handleClick(event: CustomEvent<unknown>, link: KeyedNavLink) {
    onLinkClick?.(event, link)
    dispatch('linkClick', { event, link })
  }
</script>

<nav aria-label="Extensions">
  {#each links as link (link.key)}
    <Button
      class="extension-link"
      variant="subtle"
      on:click={(event) => handleClick(event, link)}
    >
      {link.name}
    </Button>
  {/each}
</nav>

<style scoped>
  nav {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    overflow: hidden auto;
  }
</style>
