// src/App.tsx
import {
  Button,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  MenuPopover,
  MenuTrigger,
  Tab,
  TabList,
  Toolbar,
  ToolbarButton,
  makeStyles,
} from '@fluentui/react-components';
import { useEffect, useMemo, useState } from 'react';
import BuildInfo from './BuildInfo';
import Extension from './Extension';
import Extensions from './Extensions';
import ServerInfo from './ServerInfo';
import type { KeyedNavLink } from './types';
import { isExtensionInfo } from './utils';

const useStyles = makeStyles({
  tabPanel: {
    padding: '10px',
  },
  stack: {
    display: 'flex',
    flexDirection: 'row',
    gap: '1rem',
  },
  grow: {
    flexGrow: 1,
  },
});

const enum Environment {
  Public = 'https://hosting.portal.azure.net/api/diagnostics',
  Fairfax = 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics',
  Mooncake = 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics',
}

const App: React.FC = () => {
  const styles = useStyles();
  const [diagnostics, setDiagnostics] = useState<Diagnostics>();
  const [extension, setExtension] = useState<ExtensionInfo>();
  const [environment, setEnvironment] = useState<Environment>(
    Environment.Public
  );
  const [selectedTab, setSelectedTab] = useState<string>('extensions');

  const environmentName = useMemo(() => {
    switch (environment) {
      case Environment.Public:
        return 'Public Cloud';
      case Environment.Fairfax:
        return 'Fairfax';
      case Environment.Mooncake:
        return 'Mooncake';
      default:
        return 'Select environment';
    }
  }, [environment]);

  const showPaasServerless = useMemo(
    () => isExtensionInfo(diagnostics?.extensions['paasserverless']),
    [diagnostics?.extensions]
  );

  const environments = useMemo(
    () => [
      {
        key: 'public',
        text: 'Public Cloud',
        selected: environment === Environment.Public,
        onClick: () => {
          setEnvironment(Environment.Public);
          setExtension(undefined);
        },
      },
      {
        key: 'fairfax',
        text: 'Fairfax',
        selected: environment === Environment.Fairfax,
        onClick: () => {
          setEnvironment(Environment.Fairfax);
          setExtension(undefined);
        },
      },
      {
        key: 'mooncake',
        text: 'Mooncake',
        selected: environment === Environment.Mooncake,
        onClick: () => {
          setEnvironment(Environment.Mooncake);
          setExtension(undefined);
        },
      },
    ],
    [environment]
  );

  useEffect(() => {
    const getDiagnostics = async () => {
      const response = await fetch(environment);
      setDiagnostics(await response.json());
    };
    getDiagnostics();
  }, [environment]);

  if (!diagnostics) {
    return null;
  }

  const { buildInfo, extensions, serverInfo } = diagnostics;

  const handleLinkClick = (_?: React.MouseEvent, item?: KeyedNavLink) => {
    if (item) {
      const extension = extensions[item.key];
      if (isExtensionInfo(extension)) {
        setExtension(extension);
      }
    }
  };

  return (
    <>
      <Toolbar>
        <Menu>
          <MenuTrigger disableButtonEnhancement>
            <MenuButton>{environmentName}</MenuButton>
          </MenuTrigger>
          <MenuPopover>
            <MenuList>
              {environments.map(env => (
                <MenuItem
                  key={env.key}
                  onClick={env.onClick}
                  aria-checked={env.selected}
                  role="menuitemradio"
                >
                  {env.text}
                </MenuItem>
              ))}
            </MenuList>
          </MenuPopover>
        </Menu>
        {showPaasServerless && (
          <ToolbarButton
            key="paasserverless"
            onClick={() => {
              const paasserverless = diagnostics?.extensions['paasserverless'];
              if (isExtensionInfo(paasserverless)) {
                setExtension(paasserverless);
              }
            }}
          >
            paasserverless
          </ToolbarButton>
        )}
        <ToolbarButton
          key="websites"
          onClick={() => {
            const websites = diagnostics?.extensions['websites'];
            if (isExtensionInfo(websites)) {
              setExtension(websites);
            }
          }}
        >
          websites
        </ToolbarButton>
      </Toolbar>
      <TabList
        selectedValue={selectedTab}
        onTabSelect={(_, data) => setSelectedTab(data.value as string)}
      >
        <Tab value="extensions">Extensions</Tab>
        <Tab value="build">Build Information</Tab>
        <Tab value="server">Server Information</Tab>
      </TabList>
      {selectedTab === 'extensions' && (
        <div className={styles.tabPanel}>
          <div className={styles.stack}>
            <div>
              <Extensions
                extensions={extensions}
                onLinkClick={handleLinkClick}
              />
            </div>
            <div className={styles.grow}>
              {extension && <Extension {...extension} />}
            </div>
          </div>
        </div>
      )}
      {selectedTab === 'build' && (
        <div className={styles.tabPanel}>
          <BuildInfo {...buildInfo} />
        </div>
      )}
      {selectedTab === 'server' && (
        <div className={styles.tabPanel}>
          <ServerInfo {...serverInfo} />
        </div>
      )}
    </>
  );
};

export default App;

// packages/vuetify/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { VIcon } from 'vuetify/components'
import type { Diagnostics } from './App.types'
import BuildInfoTable from './BuildInfoTable.vue'
import ExtensionItem from './ExtensionItem.vue'
import type { ExtensionInfo } from './ExtensionItems.types'
import ExtensionItems from './ExtensionItems.vue'
import ServerInfoTable from './ServerInfoTable.vue'
import { isExtensionInfo } from './utils'
import type { KeyedNavLink } from './types'

type Environment =
  | 'https://hosting.portal.azure.net/api/diagnostics'
  | 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics'
  | 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics'

const Environments = {
  Public: 'https://hosting.portal.azure.net/api/diagnostics' as Environment,
  Fairfax: 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics' as Environment,
  Mooncake: 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics' as Environment,
} as const

const diagnostics = ref<Diagnostics | undefined>(undefined)
const extension = ref<ExtensionInfo | undefined>(undefined)
const environment = ref<Environment>(Environments.Public)
const selectedTab = ref('extensions')
const menuOpen = ref(false)

const environmentName = computed(() => {
  switch (environment.value) {
    case Environments.Public:
      return 'Public Cloud'
    case Environments.Fairfax:
      return 'Fairfax'
    case Environments.Mooncake:
      return 'Mooncake'
    default:
      return 'Select environment'
  }
})

const showPaasServerless = computed(() =>
  isExtensionInfo(diagnostics.value?.extensions?.['paasserverless'])
)

const environments = [
  {
    key: 'public',
    text: 'Public Cloud',
    value: Environments.Public,
  },
  {
    key: 'fairfax',
    text: 'Fairfax',
    value: Environments.Fairfax,
  },
  {
    key: 'mooncake',
    text: 'Mooncake',
    value: Environments.Mooncake,
  },
]

const fetchDiagnostics = async () => {
  const response = await fetch(environment.value)
  diagnostics.value = await response.json()
}

watch(environment, () => {
  extension.value = undefined
  fetchDiagnostics()
})

onMounted(fetchDiagnostics)

const handleLinkClick = (_: KeyboardEvent | MouseEvent, link: KeyedNavLink) => {
  if (link) {
    const ext = diagnostics.value?.extensions?.[link.key]
    if (isExtensionInfo(ext)) {
      extension.value = ext
    }
  }
}

const selectExtension = (key: string) => {
  const ext = diagnostics.value?.extensions?.[key]
  if (isExtensionInfo(ext)) {
    extension.value = ext
  }
}
</script>

<template>
  <v-app class="flexbox">
    <v-toolbar>
      <v-menu v-model="menuOpen">
        <template #activator="{ props }">
          <v-btn v-bind="props" variant="text">
            {{ environmentName }}
            <v-icon>{{ menuOpen ? 'mdi-chevron-up' : 'mdi-chevron-down' }}</v-icon>
          </v-btn>
        </template>
        <v-list>
          <v-list-item
            v-for="env in environments"
            :key="env.key"
            @click="
              () => {
                environment = env.value
                extension = undefined
              }
            "
            :aria-checked="environment === env.value"
            role="menuitemradio"
          >
            {{ env.text }}
          </v-list-item>
        </v-list>
      </v-menu>
      <v-btn
        v-if="showPaasServerless"
        variant="text"
        @click="() => selectExtension('paasserverless')"
      >
        paasserverless
      </v-btn>
      <v-btn variant="text" @click="() => selectExtension('websites')"> websites </v-btn>
    </v-toolbar>
    <v-tabs v-model="selectedTab">
      <v-tab value="extensions">Extensions</v-tab>
      <v-tab value="build">Build Information</v-tab>
      <v-tab value="server">Server Information</v-tab>
    </v-tabs>
    <div class="tab-panel">
      <v-tabs-window v-model="selectedTab">
        <v-tabs-window-item value="extensions">
          <div class="stack">
            <div class="extensions">
              <ExtensionItems
                v-if="diagnostics?.extensions"
                :extensions="diagnostics.extensions"
                :onLinkClick="handleLinkClick"
              />
            </div>
            <div class="extension">
              <ExtensionItem v-if="extension" v-bind="extension" />
            </div>
          </div>
        </v-tabs-window-item>
        <v-tabs-window-item value="build">
          <BuildInfoTable v-if="diagnostics?.buildInfo" v-bind="diagnostics.buildInfo" />
        </v-tabs-window-item>
        <v-tabs-window-item value="server">
          <ServerInfoTable v-if="diagnostics?.serverInfo" v-bind="diagnostics.serverInfo" />
        </v-tabs-window-item>
      </v-tabs-window>
    </div>
  </v-app>
</template>

<style>
html,
body,
#app {
  height: 100%;
}

html,
body {
  margin: 0;
  padding: 0;
}
</style>

<style scoped>
:deep(.v-window),
:deep(.v-window-item) {
  height: 100%;
}

.extension,
.extensions {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  max-height: max-content;
  overflow-y: auto;
  padding: 0.25rem;
}

.extension {
  flex-grow: 1;
}

.flexbox {
  height: 100%;
}

.flexbox > ::deep(.v-application__wrap) {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.stack {
  display: flex;
  flex-direction: row;
  gap: 1rem;
  height: 100%;
}

.tab-panel {
  box-sizing: border-box;
  flex: 1;
  overflow-y: auto;
}
</style>
