// packages/vuetify/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { VIcon } from 'vuetify/components'
import type { Diagnostics } from './App.types'
import BuildInfoTable from './BuildInfoTable.vue'
import ExtensionItem from './ExtensionItem.vue'
import type { ExtensionInfo } from './ExtensionItems.types'
import ExtensionItems from './ExtensionItems.vue'
import ServerInfoTable from './ServerInfoTable.vue'
import { isExtensionInfo } from './utils'
import type { KeyedNavLink } from './types'

type Environment =
  | 'https://hosting.portal.azure.net/api/diagnostics'
  | 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics'
  | 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics'

const Environments = {
  Public: 'https://hosting.portal.azure.net/api/diagnostics' as Environment,
  Fairfax: 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics' as Environment,
  Mooncake: 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics' as Environment,
} as const

const diagnostics = ref<Diagnostics | undefined>(undefined)
const extension = ref<ExtensionInfo | undefined>(undefined)
const environment = ref<Environment>(Environments.Public)
const selectedTab = ref('extensions')
const menuOpen = ref(false)

const environmentName = computed(() => {
  switch (environment.value) {
    case Environments.Public:
      return 'Public Cloud'
    case Environments.Fairfax:
      return 'Fairfax'
    case Environments.Mooncake:
      return 'Mooncake'
    default:
      return 'Select environment'
  }
})

const showPaasServerless = computed(() =>
  isExtensionInfo(diagnostics.value?.extensions?.['paasserverless'])
)

const environments = [
  {
    key: 'public',
    text: 'Public Cloud',
    value: Environments.Public,
  },
  {
    key: 'fairfax',
    text: 'Fairfax',
    value: Environments.Fairfax,
  },
  {
    key: 'mooncake',
    text: 'Mooncake',
    value: Environments.Mooncake,
  },
]

const fetchDiagnostics = async () => {
  const response = await fetch(environment.value)
  diagnostics.value = await response.json()
}

watch(environment, () => {
  extension.value = undefined
  fetchDiagnostics()
})

onMounted(fetchDiagnostics)

const handleLinkClick = (_: KeyboardEvent | MouseEvent, link: KeyedNavLink) => {
  if (link) {
    const ext = diagnostics.value?.extensions?.[link.key]
    if (isExtensionInfo(ext)) {
      extension.value = ext
    }
  }
}

const selectExtension = (key: string) => {
  const ext = diagnostics.value?.extensions?.[key]
  if (isExtensionInfo(ext)) {
    extension.value = ext
  }
}
</script>

<template>
  <v-app class="flexbox">
    <v-toolbar>
      <v-menu v-model="menuOpen">
        <template #activator="{ props }">
          <v-btn v-bind="props" variant="text">
            {{ environmentName }}
            <v-icon>{{ menuOpen ? 'mdi-chevron-up' : 'mdi-chevron-down' }}</v-icon>
          </v-btn>
        </template>
        <v-list>
          <v-list-item
            v-for="env in environments"
            :key="env.key"
            @click="
              () => {
                environment = env.value
                extension = undefined
              }
            "
            :aria-checked="environment === env.value"
            role="menuitemradio"
          >
            {{ env.text }}
          </v-list-item>
        </v-list>
      </v-menu>
      <v-btn
        v-if="showPaasServerless"
        variant="text"
        @click="() => selectExtension('paasserverless')"
      >
        paasserverless
      </v-btn>
      <v-btn variant="text" @click="() => selectExtension('websites')"> websites </v-btn>
    </v-toolbar>
    <v-tabs v-model="selectedTab">
      <v-tab value="extensions">Extensions</v-tab>
      <v-tab value="build">Build Information</v-tab>
      <v-tab value="server">Server Information</v-tab>
    </v-tabs>
    <div class="tab-panel">
      <v-tabs-window v-model="selectedTab">
        <v-tabs-window-item value="extensions">
          <div class="stack">
            <div class="extensions">
              <ExtensionItems
                v-if="diagnostics?.extensions"
                :extensions="diagnostics.extensions"
                :onLinkClick="handleLinkClick"
              />
            </div>
            <div class="extension">
              <ExtensionItem v-if="extension" v-bind="extension" />
            </div>
          </div>
        </v-tabs-window-item>
        <v-tabs-window-item value="build">
          <BuildInfoTable v-if="diagnostics?.buildInfo" v-bind="diagnostics.buildInfo" />
        </v-tabs-window-item>
        <v-tabs-window-item value="server">
          <ServerInfoTable v-if="diagnostics?.serverInfo" v-bind="diagnostics.serverInfo" />
        </v-tabs-window-item>
      </v-tabs-window>
    </div>
  </v-app>
</template>

<style>
html,
body,
#app {
  height: 100%;
}

html,
body {
  margin: 0;
  padding: 0;
}
</style>

<style scoped>
:deep(.v-window),
:deep(.v-window-item) {
  height: 100%;
}

.extension,
.extensions {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  max-height: max-content;
  overflow-y: auto;
  padding: 0.25rem;
}

.extension {
  flex-grow: 1;
}

.flexbox {
  height: 100%;
}

.flexbox > ::deep(.v-application__wrap) {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.stack {
  display: flex;
  flex-direction: row;
  gap: 1rem;
  height: 100%;
}

.tab-panel {
  box-sizing: border-box;
  flex: 1;
  overflow-y: auto;
}
</style>

// packages/spectrum/src/App.tsx
import {
  ActionButton,
  InlineAlert,
  Item,
  Menu,
  MenuTrigger,
  ProgressCircle,
  TabList,
  Tabs,
} from "@adobe/react-spectrum";
import { Activity, useCallback, useMemo, useState } from "react";
import useSWR from "swr";
import BuildInfo from "./BuildInfo";
import Extension from "./Extension";
import Extensions from "./Extensions";
import ServerInfo from "./ServerInfo";
import { isExtensionInfo } from "./utils";

import styles from "./App.module.css";

const Environment = {
  Public: "https://hosting.portal.azure.net/api/diagnostics",
  Fairfax: "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics",
  Mooncake: "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics",
} as const;

type EnvironmentUrl = (typeof Environment)[keyof typeof Environment];

const App: React.FC = () => {
  const [extension, setExtension] = useState<ExtensionInfo>();
  const [environment, setEnvironment] = useState<EnvironmentUrl>(
    Environment.Public
  );
  const [selectedTab, setSelectedTab] = useState<SelectedTab>("extensions");

  const {
    data: diagnostics,
    error,
    isLoading,
  } = useSWR<Diagnostics>(environment, async (environment: string) => {
    const response = await fetch(environment);
    if (!response.ok) {
      throw new Error(`Failed to fetch diagnostics: ${response.statusText}`);
    }

    return response.json();
  });

  const environmentName = useMemo(() => {
    switch (environment) {
      case Environment.Public:
        return "Public Cloud";
      case Environment.Fairfax:
        return "Fairfax";
      case Environment.Mooncake:
        return "Mooncake";
      default:
        return "Select environment";
    }
  }, [environment]);

  const showPaasServerless = useMemo(
    () => isExtensionInfo(diagnostics?.extensions["paasserverless"]),
    [diagnostics?.extensions]
  );

  const environments = useMemo(
    () => [
      {
        key: "public",
        text: "Public Cloud",
        selected: environment === Environment.Public,
        onClick: () => {
          setEnvironment(Environment.Public);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
      {
        key: "fairfax",
        text: "Fairfax",
        selected: environment === Environment.Fairfax,
        onClick: () => {
          setEnvironment(Environment.Fairfax);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
      {
        key: "mooncake",
        text: "Mooncake",
        selected: environment === Environment.Mooncake,
        onClick: () => {
          setEnvironment(Environment.Mooncake);
          setExtension(undefined);
          setSelectedTab("extensions");
        },
      },
    ],
    [environment]
  );

  const handleLinkClick = useCallback(
    (_?: React.MouseEvent, item?: KeyedNavLink) => {
      if (item) {
        const extension = diagnostics?.extensions[item.key];
        if (isExtensionInfo(extension)) {
          setExtension(extension);
        }
      }
    },
    [diagnostics?.extensions]
  );

  return (
    <div className={styles.flexbox}>
      <div style={{ display: "flex", gap: "8px", padding: "8px" }}>
        <MenuTrigger>
          <ActionButton>{environmentName}</ActionButton>
          <Menu
            onAction={(key) => {
              environments.find((e) => e.key === key)?.onClick();
            }}
          >
            {environments.map((env) => (
              <Item key={env.key}>{env.text}</Item>
            ))}
          </Menu>
        </MenuTrigger>
        <Activity mode={showPaasServerless ? "visible" : "hidden"}>
          <ActionButton
            onPress={() => {
              const paasserverless = diagnostics?.extensions["paasserverless"];
              if (isExtensionInfo(paasserverless)) {
                setExtension(paasserverless);
                setSelectedTab("extensions");
              }
            }}
          >
            paasserverless
          </ActionButton>
        </Activity>
        <ActionButton
          onPress={() => {
            const websites = diagnostics?.extensions["websites"];
            if (isExtensionInfo(websites)) {
              setExtension(websites);
              setSelectedTab("extensions");
            }
          }}
        >
          websites
        </ActionButton>
      </div>
      <Tabs
        aria-label="Information Tabs"
        selectedKey={selectedTab}
        onSelectionChange={(key) => setSelectedTab(key)}
      >
        <TabList>
          <Item key="extensions">Extensions</Item>
          <Item key="build">Build Information</Item>
          <Item key="server">Server Information</Item>
        </TabList>
      </Tabs>
      <Activity mode={!error && isLoading ? "visible" : "hidden"}>
        <div className={(styles["tab-panel"], styles["centered"])}>
          <ProgressCircle aria-label="Loading..." isIndeterminate />
        </div>
      </Activity>
      <Activity mode={error && !isLoading ? "visible" : "hidden"}>
        <div className={(styles["tab-panel"], styles["centered"])}>
          <InlineAlert variant="negative">Error loading data</InlineAlert>
        </div>
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "extensions"
            ? "visible"
            : "hidden"
        }
      >
        {diagnostics?.extensions && (
          <div className={styles["tab-panel"]} role="tabpanel">
            <div className={styles.stack}>
              <Extensions
                extensions={diagnostics.extensions}
                onLinkClick={handleLinkClick}
              />
              {extension && <Extension {...extension} />}
            </div>
          </div>
        )}
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "build" ? "visible" : "hidden"
        }
      >
        {diagnostics?.buildInfo && (
          <div className={styles["tab-panel"]} role="tabpanel">
            <BuildInfo {...diagnostics.buildInfo} />
          </div>
        )}
      </Activity>
      <Activity
        mode={
          !error && !isLoading && selectedTab === "server"
            ? "visible"
            : "hidden"
        }
      >
        {diagnostics?.serverInfo && (
          <div className={styles["tab-panel"]} role="tabpanel">
            <ServerInfo {...diagnostics.serverInfo} />
          </div>
        )}
      </Activity>
    </div>
  );
};

export default App;
