// packages/quasar/src/components/BuildInfo.vue
<template>
  <div>
    <q-markup-table flat>
      <thead>
        <tr>
          <th class="text-left">Name</th>
          <th class="text-left">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in rows" :key="row.name">
          <td>{{ row.name }}</td>
          <td>{{ row.value }}</td>
        </tr>
      </tbody>
    </q-markup-table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { BuildInfoProps } from './models';

const props = defineProps<BuildInfoProps>();

const rows = computed(() => [{ name: 'Build Version', value: props.buildVersion }]);
</script>

// packages/skeleton/src/lib/components/BuildInfo.svelte
<script lang="ts">
	export let buildVersion: string;
</script>

<table class="divide-surface-2 min-w-full divide-y">
	<caption class="sr-only">Build Info</caption>
	<thead class="bg-surface-1">
		<tr>
			<th class="px-4 py-2 text-left">Name</th>
			<th class="px-4 py-2 text-left">Value</th>
		</tr>
	</thead>
	<tbody class="[&>tr]:border-surface-2 [&>tr]:border-b">
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Build Version</td>
			<td class="px-4 py-2">{buildVersion}</td>
		</tr>
	</tbody>
</table>

<h2 id="buildinfo-heading" class="sr-only">Build Info</h2>
