// packages/carbon/src/lib/components/Configuration.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { config }: ConfigurationProps = $props();

	const headers = [
		{ key: 'key', value: 'Key', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived(Object.entries(config).map(([key, value]) => ({ id: key, key, value })));
</script>

<h2 id="configuration">Configuration</h2>
<DataTable aria-labelledby="configuration" {headers} {rows} />

// packages/element-plus/app/components/Configuration.vue
<template>
    <h2 id="configuration">Configuration</h2>
    <el-table :data="rows" style="width: 100%" aria-labelledby="configuration">
        <el-table-column prop="key" label="Key" show-overflow-tooltip />
        <el-table-column prop="value" label="Value" show-overflow-tooltip />
    </el-table>
</template>

<script setup lang="ts">
import type { ConfigurationProps } from "@/types"

const props = defineProps<ConfigurationProps>()

const rows = computed(() =>
    Object.entries(props.config).map(([key, value]) => ({ key, value }))
)
</script>
