// packages/skeleton/src/lib/components/Configuration.svelte
<script lang="ts">
	export let config: Record<string, string>;
</script>

<div>
	<h2 id="configuration" class="mb-2 text-sm font-semibold">Configuration</h2>
	<table
		aria-labelledby="configuration"
		class="divide-surface-2 min-w-full divide-y"
	>
		<thead class="bg-surface-1">
			<tr>
				<th class="px-4 py-2 text-left">Key</th>
				<th class="px-4 py-2 text-left">Value</th>
			</tr>
		</thead>
		<tbody class="[&>tr]:border-surface-2 [&>tr]:border-b">
			{#each Object.entries(config) as [key, value] (key)}
				<tr class="[&:hover]:preset-tonal-primary">
					<td class="px-4 py-2">{key}</td>
					<td class="px-4 py-2">{value}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>

// packages/quasar/src/components/Configuration.vue
<template>
  <div>
    <h2>Configuration</h2>
    <q-markup-table flat>
      <thead>
        <tr>
          <th class="text-left">Key</th>
          <th class="text-left">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="[key, value] in configEntries" :key="key">
          <td>{{ key }}</td>
          <td>{{ value }}</td>
        </tr>
      </tbody>
    </q-markup-table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ConfigurationProps } from './models';

const props = defineProps<ConfigurationProps>();

const configEntries = computed(() => Object.entries(props.config ?? {}));
</script>
