// packages/grommet/src/Extensions.tsx
import { byKey, isExtensionInfo, toNavLink } from "./utils";
import { Nav, Button } from "grommet";

const Extensions: React.FC<ExtensionsProps> = ({ extensions, onLinkClick }) => {
  const links = Object.values(extensions)
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey);

  return (
    <Nav
      aria-label="Extensions"
      className="extension-root overflow-x-hidden"
      direction="column"
      gap="small"
      pad="small"
    >
      {links.map((link) => (
        <Button
          key={link.key}
          label={link.name}
          plain
          onClick={(e) => onLinkClick?.(e, link)}
        />
      ))}
    </Nav>
  );
};

export default Extensions;

// packages/quasar/src/components/Extensions.vue
<template>
  <nav class="flex column extensions">
    <q-list aria-label="Extensions">
      <q-item v-for="link in links" :key="link.key" clickable @click="handleClick(link)">
        <q-item-section>
          {{ link.name }}
        </q-item-section>
      </q-item>
    </q-list>
  </nav>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ExtensionsProps, KeyedNavLink } from './models';
import { byKey, isExtensionInfo, toNavLink } from '../utils/extensions';

const props = defineProps<ExtensionsProps>();

const links = computed(() =>
  Object.values(props.extensions ?? {})
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey),
);

function handleClick(link: KeyedNavLink) {
  props.onLinkClick?.(link);
}
</script>

<style scoped>
.extensions {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow-x: hidden;
  overflow-y: auto;
}
</style>
