// packages/skeleton/src/lib/components/ServerInfo.svelte
<script lang="ts">
	export let deploymentId: string;
	export let extensionSync: { totalSyncAllCount: number };
	export let hostname: string;
	export let nodeVersions: string;
	export let serverId: string;
	export let uptime: number;
</script>

<table class="divide-surface-2 min-w-full divide-y">
	<caption class="sr-only">Server Info</caption>
	<thead class="bg-surface-1">
		<tr>
			<th class="px-4 py-2 text-left">Name</th>
			<th class="px-4 py-2 text-left">Value</th>
		</tr>
	</thead>
	<tbody class="[&>tr]:border-surface-2 [&>tr]:border-b">
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Hostname</td>
			<td class="px-4 py-2">{hostname}</td>
		</tr>
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Uptime</td>
			<td class="px-4 py-2">{uptime}</td>
		</tr>
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Server ID</td>
			<td class="px-4 py-2">{serverId}</td>
		</tr>
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Deployment ID</td>
			<td class="px-4 py-2">{deploymentId}</td>
		</tr>
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Node Versions</td>
			<td class="px-4 py-2">{nodeVersions}</td>
		</tr>
		<tr class="[&:hover]:preset-tonal-primary">
			<td class="px-4 py-2">Extension Sync | Total Sync All Count</td>
			<td class="px-4 py-2">{extensionSync.totalSyncAllCount}</td>
		</tr>
	</tbody>
</table>

<h2 id="serverinfo-heading" class="sr-only">Server Info</h2>

// packages/quasar/src/components/ServerInfo.vue
<template>
  <div>
    <q-markup-table flat>
      <thead>
        <tr>
          <th class="text-left">Name</th>
          <th class="text-left">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Hostname</td>
          <td>{{ props.hostname }}</td>
        </tr>
        <tr v-if="props.uptime !== undefined">
          <td>Uptime</td>
          <td>{{ props.uptime }}</td>
        </tr>
        <tr>
          <td>Server ID</td>
          <td>{{ props.serverId }}</td>
        </tr>
        <tr>
          <td>Deployment ID</td>
          <td>{{ props.deploymentId }}</td>
        </tr>
        <tr v-if="props.nodeVersions !== undefined">
          <td>Node Versions</td>
          <td>{{ props.nodeVersions }}</td>
        </tr>
        <tr>
          <td>Extension Sync | Total Sync All Count</td>
          <td>{{ props.extensionSync.totalSyncAllCount }}</td>
        </tr>
      </tbody>
    </q-markup-table>
  </div>
</template>

<script setup lang="ts">
import type { ServerInfoProps } from './models';

const props = defineProps<ServerInfoProps>();
</script>
