// packages/solidjs-suid/src/App.tsx
import {
  Box,
  Button,
  ButtonGroup,
  Toolbar,
  Menu,
  MenuItem,
} from "@suid/material";
import ExpandMore from "@suid/icons-material/ExpandMore";
import { createEffect, createMemo, createSignal, For, Show } from "solid-js";
import BuildInfo from "./BuildInfo";
import Extension from "./Extension";
import Extensions from "./Extensions";
import ServerInfo from "./ServerInfo";
import { isExtensionInfo } from "./utils";

const Environment = {
  Public: "https://hosting.portal.azure.net/api/diagnostics",
  Fairfax: "https://hosting.azureportal.usgovcloudapi.net/api/diagnostics",
  Mooncake: "https://hosting.azureportal.chinacloudapi.cn/api/diagnostics",
};

function App() {
  const [diagnostics, setDiagnostics] = createSignal<Diagnostics>();
  const [extension, setExtension] = createSignal<ExtensionInfo>();
  const [environment, setEnvironment] = createSignal(Environment.Public);
  const [selectedTab, setSelectedTab] = createSignal("extensions");

  const showPaasServerless = createMemo(() =>
    isExtensionInfo(diagnostics()?.extensions?.["paasserverless"])
  );

  const environments = [
    {
      key: "public",
      text: "Public Cloud",
      selected: () => environment() === Environment.Public,
      onClick: () => {
        setEnvironment(Environment.Public);
        setExtension(undefined);
        setSelectedTab("extensions");
      },
    },
    {
      key: "fairfax",
      text: "Fairfax",
      selected: () => environment() === Environment.Fairfax,
      onClick: () => {
        setEnvironment(Environment.Fairfax);
        setExtension(undefined);
        setSelectedTab("extensions");
      },
    },
    {
      key: "mooncake",
      text: "Mooncake",
      selected: () => environment() === Environment.Mooncake,
      onClick: () => {
        setEnvironment(Environment.Mooncake);
        setExtension(undefined);
        setSelectedTab("extensions");
      },
    },
  ];

  createEffect(() => {
    const getDiagnostics = async () => {
      const response = await fetch(environment());
      setDiagnostics(await response.json());
    };
    getDiagnostics();
  });

  const handleLinkClick = (_: unknown, item: KeyedNavLink) => {
    if (item) {
      const ext = diagnostics()?.extensions?.[item.key];
      if (isExtensionInfo(ext)) {
        setExtension(ext);
      }
    }
  };

  const [menuAnchor, setMenuAnchor] = createSignal<HTMLElement>();
  const [menuOpen, setMenuOpen] = createSignal(false);

  const handleMenuOpen = (event: MouseEvent): void => {
    setMenuAnchor(event.currentTarget as HTMLButtonElement);
    setMenuOpen(true);
  };

  const handleMenuClose = () => {
    setMenuOpen(false);
    setMenuAnchor(undefined);
  };

  return (
    <Box
      sx={{
        display: "flex",
        flexDirection: "column",
        gap: "0.25rem",
        height: "100vh",
      }}
    >
      <Toolbar>
        <Button variant="contained" onClick={handleMenuOpen}>
          {environments.find((env) => env.selected())?.text ??
            "Select Environment"}
          <span
            class={`chevron-icon${menuOpen() ? " open" : ""}`}
            style={{ display: "inline-flex", transition: "transform 0.3s" }}
          >
            <ExpandMore />
          </span>
        </Button>
        <Menu
          anchorEl={menuAnchor()}
          open={menuOpen()}
          onClose={handleMenuClose}
        >
          <For each={environments}>
            {(env) => (
              <MenuItem
                selected={env.selected()}
                onClick={() => {
                  env.onClick();
                  handleMenuClose();
                }}
              >
                {env.text}
              </MenuItem>
            )}
          </For>
        </Menu>
        <Show when={showPaasServerless()}>
          <Button
            onClick={() => {
              const paasserverless =
                diagnostics()?.extensions?.["paasserverless"];
              if (isExtensionInfo(paasserverless)) {
                setExtension(paasserverless);
                setSelectedTab("extensions");
              }
            }}
          >
            paasserverless
          </Button>
        </Show>
        <Button
          onClick={() => {
            const websites = diagnostics()?.extensions?.["websites"];
            if (isExtensionInfo(websites)) {
              setExtension(websites);
              setSelectedTab("extensions");
            }
          }}
        >
          websites
        </Button>
      </Toolbar>
      <ButtonGroup>
        <Button
          variant={selectedTab() === "extensions" ? "contained" : "outlined"}
          onClick={() => setSelectedTab("extensions")}
        >
          Extensions
        </Button>
        <Button
          variant={selectedTab() === "build" ? "contained" : "outlined"}
          onClick={() => setSelectedTab("build")}
        >
          Build Information
        </Button>
        <Button
          variant={selectedTab() === "server" ? "contained" : "outlined"}
          onClick={() => setSelectedTab("server")}
        >
          Server Information
        </Button>
      </ButtonGroup>
      <Show when={diagnostics()}>
        <Show when={selectedTab() === "extensions"}>
          <Box sx={{ boxSizing: "border-box", flex: "1", overflowY: "auto" }}>
            <Box
              sx={{
                display: "flex",
                flexDirection: "row",
                flexWrap: "nowrap",
                gap: "1rem",
                height: "100%",
              }}
            >
              <Extensions
                extensions={diagnostics().extensions}
                onLinkClick={handleLinkClick}
              />
              <Show when={extension()}>
                <Extension {...extension()} />
              </Show>
            </Box>
          </Box>
        </Show>
        <Show when={selectedTab() === "build"}>
          <Box sx={{ boxSizing: "border-box", flex: "1", overflowY: "auto" }}>
            <BuildInfo {...diagnostics().buildInfo} />
          </Box>
        </Show>
        <Show when={selectedTab() === "server"}>
          <Box sx={{ boxSizing: "border-box", flex: "1", overflowY: "auto" }}>
            <ServerInfo {...diagnostics().serverInfo} />
          </Box>
        </Show>
      </Show>
    </Box>
  );
}

export default App;

/* Animation for chevron icon */
import "./styles.css";

// src/App.tsx
import {
  Button,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  MenuPopover,
  MenuTrigger,
  Tab,
  TabList,
  Toolbar,
  ToolbarButton,
  makeStyles,
} from '@fluentui/react-components';
import { useEffect, useMemo, useState } from 'react';
import BuildInfo from './BuildInfo';
import Extension from './Extension';
import Extensions from './Extensions';
import ServerInfo from './ServerInfo';
import type { KeyedNavLink } from './types';
import { isExtensionInfo } from './utils';

const useStyles = makeStyles({
  tabPanel: {
    padding: '10px',
  },
  stack: {
    display: 'flex',
    flexDirection: 'row',
    gap: '1rem',
  },
  grow: {
    flexGrow: 1,
  },
});

const enum Environment {
  Public = 'https://hosting.portal.azure.net/api/diagnostics',
  Fairfax = 'https://hosting.azureportal.usgovcloudapi.net/api/diagnostics',
  Mooncake = 'https://hosting.azureportal.chinacloudapi.cn/api/diagnostics',
}

const App: React.FC = () => {
  const styles = useStyles();
  const [diagnostics, setDiagnostics] = useState<Diagnostics>();
  const [extension, setExtension] = useState<ExtensionInfo>();
  const [environment, setEnvironment] = useState<Environment>(
    Environment.Public
  );
  const [selectedTab, setSelectedTab] = useState<string>('extensions');

  const environmentName = useMemo(() => {
    switch (environment) {
      case Environment.Public:
        return 'Public Cloud';
      case Environment.Fairfax:
        return 'Fairfax';
      case Environment.Mooncake:
        return 'Mooncake';
      default:
        return 'Select environment';
    }
  }, [environment]);

  const showPaasServerless = useMemo(
    () => isExtensionInfo(diagnostics?.extensions['paasserverless']),
    [diagnostics?.extensions]
  );

  const environments = useMemo(
    () => [
      {
        key: 'public',
        text: 'Public Cloud',
        selected: environment === Environment.Public,
        onClick: () => {
          setEnvironment(Environment.Public);
          setExtension(undefined);
        },
      },
      {
        key: 'fairfax',
        text: 'Fairfax',
        selected: environment === Environment.Fairfax,
        onClick: () => {
          setEnvironment(Environment.Fairfax);
          setExtension(undefined);
        },
      },
      {
        key: 'mooncake',
        text: 'Mooncake',
        selected: environment === Environment.Mooncake,
        onClick: () => {
          setEnvironment(Environment.Mooncake);
          setExtension(undefined);
        },
      },
    ],
    [environment]
  );

  useEffect(() => {
    const getDiagnostics = async () => {
      const response = await fetch(environment);
      setDiagnostics(await response.json());
    };
    getDiagnostics();
  }, [environment]);

  if (!diagnostics) {
    return null;
  }

  const { buildInfo, extensions, serverInfo } = diagnostics;

  const handleLinkClick = (_?: React.MouseEvent, item?: KeyedNavLink) => {
    if (item) {
      const extension = extensions[item.key];
      if (isExtensionInfo(extension)) {
        setExtension(extension);
      }
    }
  };

  return (
    <>
      <Toolbar>
        <Menu>
          <MenuTrigger disableButtonEnhancement>
            <MenuButton>{environmentName}</MenuButton>
          </MenuTrigger>
          <MenuPopover>
            <MenuList>
              {environments.map(env => (
                <MenuItem
                  key={env.key}
                  onClick={env.onClick}
                  aria-checked={env.selected}
                  role="menuitemradio"
                >
                  {env.text}
                </MenuItem>
              ))}
            </MenuList>
          </MenuPopover>
        </Menu>
        {showPaasServerless && (
          <ToolbarButton
            key="paasserverless"
            onClick={() => {
              const paasserverless = diagnostics?.extensions['paasserverless'];
              if (isExtensionInfo(paasserverless)) {
                setExtension(paasserverless);
              }
            }}
          >
            paasserverless
          </ToolbarButton>
        )}
        <ToolbarButton
          key="websites"
          onClick={() => {
            const websites = diagnostics?.extensions['websites'];
            if (isExtensionInfo(websites)) {
              setExtension(websites);
            }
          }}
        >
          websites
        </ToolbarButton>
      </Toolbar>
      <TabList
        selectedValue={selectedTab}
        onTabSelect={(_, data) => setSelectedTab(data.value as string)}
      >
        <Tab value="extensions">Extensions</Tab>
        <Tab value="build">Build Information</Tab>
        <Tab value="server">Server Information</Tab>
      </TabList>
      {selectedTab === 'extensions' && (
        <div className={styles.tabPanel}>
          <div className={styles.stack}>
            <div>
              <Extensions
                extensions={extensions}
                onLinkClick={handleLinkClick}
              />
            </div>
            <div className={styles.grow}>
              {extension && <Extension {...extension} />}
            </div>
          </div>
        </div>
      )}
      {selectedTab === 'build' && (
        <div className={styles.tabPanel}>
          <BuildInfo {...buildInfo} />
        </div>
      )}
      {selectedTab === 'server' && (
        <div className={styles.tabPanel}>
          <ServerInfo {...serverInfo} />
        </div>
      )}
    </>
  );
};

export default App;
