// packages/bootstrap-vue/app/components/BuildInfo.vue
<template>
  <div>
    <BTable :items="rows" :fields="fields" small />
  </div>
</template>

<script setup lang="ts">
import type { BuildInfoProps } from "@/types/BuildInfoProps";

const props = defineProps<BuildInfoProps>();

const fields = [
  { key: "name", label: "Name" },
  { key: "value", label: "Value" }
];

const rows = computed(() => [{ name: "Build Version", value: props.buildVersion }]);
</script>

// packages/carbon/src/lib/components/BuildInfo.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { buildVersion }: BuildInfoProps = $props();

	const headers = [
		{ key: 'name', value: 'Name', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived([{ id: 'build-version', name: 'Build Version', value: buildVersion }]);
</script>

<DataTable aria-label="Build Information" {headers} {rows} />
