// packages/bootstrap-vue/app/components/Configuration.vue
<template>
  <div>
    <h2>Configuration</h2>
    <BTable :items="rows" :fields="fields" small />
  </div>
</template>

<script setup lang="ts">
import type { ConfigurationProps } from "@/types/ConfigurationProps";

const props = defineProps<ConfigurationProps>();

const fields = [
  { key: "key", label: "Key" },
  { key: "value", label: "Value" }
];

const rows = computed(() =>
  Object.entries(props.config ?? {}).map(([key, value]) => ({ key, value }))
);
</script>

// packages/carbon/src/lib/components/Configuration.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { config }: ConfigurationProps = $props();

	const headers = [
		{ key: 'key', value: 'Key', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived(Object.entries(config).map(([key, value]) => ({ id: key, key, value })));
</script>

<h2 id="configuration">Configuration</h2>
<DataTable aria-labelledby="configuration" {headers} {rows} />
