// packages/blueprint/src/Extensions.tsx
import { Tab, Tabs } from "@blueprintjs/core";
import { useState } from "react";
import { byKey, isExtensionInfo, toNavLink } from "./utils";

const Extensions: React.FC<ExtensionsProps> = ({ extensions, onLinkClick }) => {
  const links = Object.values(extensions)
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey);

  const [selectedTabId, setSelectedTabId] = useState<string>();

  return (
    <div className="extension-root">
      <Tabs
        vertical
        selectedTabId={selectedTabId}
        onChange={(tabId: string) => {
          setSelectedTabId(tabId);
          const link = links.find((l) => l.key === tabId);
          if (link) {
            onLinkClick(link);
          }
        }}
      >
        {links.map((link) => (
          <Tab
            key={link.key}
            aria-controls="extension"
            id={link.key}
            title={link.name}
          />
        ))}
      </Tabs>
    </div>
  );
};

export default Extensions;

// packages/carbon/src/lib/components/Extensions.svelte
<script lang="ts">
	import { byKey, isExtensionInfo, toNavLink } from '$lib';
	import { SideNavLink } from 'carbon-components-svelte';

	let { extensions, onLinkClick }: ExtensionsProps = $props();

	let links = $derived(
		Object.values(extensions).filter(isExtensionInfo).map(toNavLink).sort(byKey)
	);
</script>

{#each links as link (link.key)}
	<SideNavLink text={link.name} on:click={() => onLinkClick(link)} />
{/each}
