// packages/element-plus/app/components/StageDefinition.vue
<template>
    <h2 id="stage-definitions">Stage Definitions</h2>
    <el-table :data="rows" style="width: 100%" aria-labelledby="stage-definitions">
        <el-table-column prop="key" label="Key" show-overflow-tooltip />
        <el-table-column prop="value" label="Value" show-overflow-tooltip />
    </el-table>
</template>

<script setup lang="ts">
import type { StageDefinitionProps } from "@/types"

const props = defineProps<StageDefinitionProps>()

const rows = computed(() =>
    Object.entries(props.stageDefinition).map(([key, value]) => ({
        key,
        value: value.join(", ")
    }))
)
</script>

// packages/carbon/src/lib/components/StageDefinition.svelte
<script lang="ts">
	import { DataTable } from 'carbon-components-svelte';

	const { stageDefinition }: StageDefinitionProps = $props();

	const headers = [
		{ key: 'key', value: 'Key', empty: false },
		{ key: 'value', value: 'Value', empty: false }
	];

	const rows = $derived(
		Object.entries(stageDefinition).map(([key, value]) => ({
			id: key,
			key,
			value: value.join(', ')
		}))
	);
</script>

<h2 id="stage-definitions">Stage Definition</h2>
<DataTable aria-labelledby="stage-definitions" {headers} {rows} />
