// packages/quasar/src/components/Configuration.vue
<template>
  <div>
    <h2>Configuration</h2>
    <q-markup-table flat>
      <thead>
        <tr>
          <th class="text-left">Key</th>
          <th class="text-left">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="[key, value] in configEntries" :key="key">
          <td>{{ key }}</td>
          <td>{{ value }}</td>
        </tr>
      </tbody>
    </q-markup-table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ConfigurationProps } from './models';

const props = defineProps<ConfigurationProps>();

const configEntries = computed(() => Object.entries(props.config ?? {}));
</script>

// packages/smui/src/lib/components/Configuration.svelte
<script lang="ts">
	const { config }: ConfigurationProps = $props();

	const items = $derived(
		Object.entries(config).map(([key, value]) => ({ key, value }))
	);
</script>

<div>
	<h2 id="configuration" class="mdc-typography--headline5">Configuration</h2>
	<table aria-labelledby="configuration">
		<thead>
			<tr>
				<th class="mdc-typography--headline6">Key</th>
				<th class="mdc-typography--headline6">Value</th>
			</tr>
		</thead>
		<tbody>
			{#each items as item (item.key)}
				<tr>
					<td class="mdc-typography--body1">{item.key}</td>
					<td class="mdc-typography--body1">{item.value}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>
