// packages/quasar/src/components/Extension.vue
<template>
  <div class="extension">
    <h1>{{ extensionName }}</h1>
    <Configuration v-if="config" :config="config" />
    <StageDefinition v-if="stageDefinition" :stage-definition="stageDefinition" />
  </div>
</template>

<script setup lang="ts">
import type { ExtensionProps } from './models';
import Configuration from './Configuration.vue';
import StageDefinition from './StageDefinition.vue';

defineProps<ExtensionProps>();
</script>

<style scoped>
.extension {
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 1rem;
  overflow-y: auto;
}
</style>

// packages/smui/src/lib/components/Extension.svelte
<script lang="ts">
	import Configuration from './Configuration.svelte';
	import StageDefinition from './StageDefinition.svelte';

	const { extensionName, config, stageDefinition }: ExtensionProps = $props();
</script>

<div class="extension-root grow" role="tabpanel" tabindex="0">
	<h1 class="mdc-typography--headline4">{extensionName}</h1>
	{#if config}
		<Configuration {config} />
	{/if}
	{#if stageDefinition}
		<StageDefinition {stageDefinition} />
	{/if}
</div>

<style scoped>
	.extension-root {
		display: flex;
		flex-direction: column;
		margin: 4px;
		overflow-y: auto;
	}

	.grow {
		flex: 1;
	}
</style>
