// packages/bootstrap-vue/app/components/Extensions.vue
<template>
  <nav class="extensions" aria-label="Extensions">
    <div class="d-flex flex-column gap-3">
      <BLink
        v-for="link in links"
        :key="link.key"
        href="#"
        class="text-start"
        @click="handleClick(link)"
      >
        {{ link.name }}
      </BLink>
    </div>
  </nav>
</template>

<script setup lang="ts">
import type { ExtensionsProps, KeyedNavLink } from "@/types/ExtensionsProps";
import { byKey, isExtensionInfo, toNavLink } from "@/utils/extensions";

const props = defineProps<ExtensionsProps>();

const links = computed(() =>
  Object.values(props.extensions ?? {})
    .filter(isExtensionInfo)
    .map(toNavLink)
    .sort(byKey)
);

function handleClick(link: KeyedNavLink) {
  props.onLinkClick?.(link);
}
</script>

<style scoped>
.extensions {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  max-height: max-content;
  overflow-x: hidden;
  overflow-y: auto;
  padding: 0.5rem;
}
</style>

// packages/smui/src/lib/components/Extensions.svelte
<script lang="ts">
	import { byKey, isExtensionInfo, toNavLink } from '$lib';
	import List, { Item } from '@smui/list';

	const { extensions, onLinkClick }: ExtensionsProps = $props();

	const links = $derived(
		Object.values(extensions).filter(isExtensionInfo).map(toNavLink).sort(byKey)
	);
</script>

<div class="extension-root">
	<List aria-label="Extensions" class="extension-root">
		{#each links as link (link.name)}
			<Item onSMUIAction={(e) => onLinkClick?.(e, link)}>
				{link.name}
			</Item>
		{/each}
	</List>
</div>

<style scoped>
	.extension-root {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		max-height: max-content;
		overflow-y: auto;
		padding: 0.25rem;
	}
</style>
