// packages/quasar/src/components/StageDefinition.vue
<template>
  <div>
    <h2>Stage Definitions</h2>
    <q-markup-table flat>
      <thead>
        <tr>
          <th class="text-left">Key</th>
          <th class="text-left">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="entry in stageEntries" :key="entry.key">
          <td>{{ entry.key }}</td>
          <td>{{ entry.value }}</td>
        </tr>
      </tbody>
    </q-markup-table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { StageDefinitionProps } from './models';

const props = defineProps<StageDefinitionProps>();

const stageEntries = computed(() =>
  Object.entries(props.stageDefinition ?? {}).map(([key, value]) => ({
    key,
    value: value.join(', '),
  })),
);
</script>

// packages/smui/src/lib/components/StageDefinition.svelte
<script lang="ts">
	const { stageDefinition }: StageDefinitionProps = $props();

	const items = $derived(
		Object.entries(stageDefinition).map(([key, value]) => ({ key, value }))
	);
</script>

<div>
	<h2 id="stage-definitions" class="mdc-typography--headline5">
		Stage Definitions
	</h2>
	<table aria-labelledby="stage-definitions">
		<thead>
			<tr>
				<th class="mdc-typography--headline6">Key</th>
				<th class="mdc-typography--headline6">Value</th>
			</tr>
		</thead>
		<tbody>
			{#each items as item (item.key)}
				<tr>
					<td class="mdc-typography--body1">{item.key}</td>
					<td class="mdc-typography--body1">{item.value.join(', ')}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>
